# -*- coding: utf-8 -*-
"""Qualitive Content Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178Yda1rZ7IiHpMcHBPMQCUzjq3DVrQdP

**Qualitative Analysis**

Conceptual content analysis using Neoliberalism concepts
"""

# Processing the uploaded zip file, performing deductive conceptual content analysis (make sure you put all the files in a zip)
# using the provided coding dictionary. Outputs saved as CSVs and brief summary printed.
# Uses simple sentence splitting and keyword matching (case-insensitive).
# If a file type can't be read, it will be reported.

import os, zipfile, re, json, traceback
from collections import defaultdict, Counter
import pandas as pd

zip_path = '/content/text data.zip' # adjust this
extract_dir = '/mnt/data/text_data_unzipped'

# Prepare coding dictionaries (lowercased terms / phrases)
concept_keywords = {
    'institutional_arrangements': [
        "institution", "institutional", "institutionalize", "regime", "regime complex", "treaty", "treaties", "agreement", "agreements",
        "accord", "pact", "convention", "charter", "protocol", "memorandum of understanding", "mou", "code of conduct", "coc",
        "declaration", "communiqu", "joint statement", "framework", "framework agreement", "mechanism", "forum", "council", "committee",
        "working group", "secretariat", "rules-based", "rule of law", "governance", "norm", "procedure", "dispute settlement", "arbitration",
        "mediation", "dialogue mechanism", "dialogue framework", "consultation", "confidence-building measure", "cbm", "hotline", "guideline",
        "roadmap", "road map", "action plan", "poa", "agenda", "meeting", "summit", "ministerial", "track-1", "arff", "arf", "admm", "admm-plus", "eas",
        "doc", "tac", "rcep", "mpac", "bri", "ratify", "ratified", "ratification", "sign", "signed", "signing", "implement", "implementation", "committee of permanent representatives", "cpr"
    ],
    'interdependence': [
        "interdependence", "interdependent", "mutual dependence", "mutual reliance", "economic ties", "trade ties", "trade link", "trade links", "trade flow", "trade flows",
        "supply chain", "value chain", "production network", "connectivity", "integration", "fdi", "foreign direct investment", "investment flow", "investment flows",
        "mutual benefits", "shared interests", "complementarity", "intertwined", "linkage", "linkages", "dependenc", "exposure", "openness", "open economies", "cross-border",
        "people-to-people", "tourism flow", "visitor arrivals", "migration", "energy interdependence", "maritime trade routes", "sea lane", "slog", "sLOC", "s-l-o-c", "sea lanes"
    ],
    'absolute_gains': [
        "absolute gain", "absolute gains", "mutual benefit", "mutual benefits", "win-win", "positive-sum", "positive sum", "shared prosperity", "common development",
        "mutual advantage", "mutual advantages", "cooperative partnership", "cooperative partnerships", "both sides benefit", "shared growth", "deliverable", "deliverables",
        "pragmatic cooperation", "practical cooperation"
    ],
    'shadow_of_future': [
        "shadow of the future", "long-term cooperation", "long term cooperation", "long-term partnership", "long term partnership", "long-term commitment",
        "long term commitment", "sustained engagement", "ongoing dialogue", "regularized meetings", "regularised meetings", "regularized meeting", "repeated interactions",
        "repeated interaction", "trust-building", "trust building", "build trust", "confidence-building", "roadmap 2030", "vision 2030", "five-year plan", "five year plan",
        "long horizon", "predictability", "durability", "continuity", "forward-looking", "forward looking", "commitment to continue", "pledge to", "will continue", "next meeting", "future meeting", "follow-up meeting", "next round"
    ]
}

# Normalize keywords for matching
for k in concept_keywords:
    concept_keywords[k] = list(set([kw.lower() for kw in concept_keywords[k]]))

# Utility: robust file reader for .txt and .docx (if python-docx available)
def read_file_content(path):
    try:
        if path.lower().endswith('.txt') or path.lower().endswith('.text') or path.lower().endswith('.md') or path.lower().endswith('.csv'):
            try:
                with open(path, 'r', encoding='utf-8') as f:
                    return f.read(), None
            except Exception:
                with open(path, 'r', encoding='latin-1') as f:
                    return f.read(), None
        elif path.lower().endswith('.docx'):
            try:
                from docx import Document
                doc = Document(path)
                full = "\n".join([p.text for p in doc.paragraphs])
                return full, None
            except Exception as e:
                return None, f"Failed to read docx: {e}"
        else:
            # attempt to read as text as a last resort
            try:
                with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                    return f.read(), None
            except Exception as e:
                return None, str(e)
    except Exception as e:
        return None, str(e)

# Sentence splitter using regex (keeps simple punctuation splits)
def split_into_sentences(text):
    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text.strip())
    # Split on punctuation followed by whitespace and a capital letter OR end of string
    sentences = re.split(r'(?<=[\.\?\!])\s+', text)
    sentences = [s.strip() for s in sentences if s.strip()!='']
    return sentences

# Match keywords: return matched keywords list
def match_concept(sentence, keywords):
    s = sentence.lower()
    matches = []
    for kw in keywords:
        # simple containment check, but require word boundary for single words longer than 2 chars
        if len(kw.split()) == 1 and len(kw) > 2:
            pattern = r'\\b' + re.escape(kw) + r'\\b'
            if re.search(pattern, s):
                matches.append(kw)
        else:
            if kw in s:
                matches.append(kw)
    return matches

# Unzip file
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir, exist_ok=True)

text_file_paths = []
zip_file_count = 0
with zipfile.ZipFile(zip_path, 'r') as z:
    namelist = z.namelist()
    # count text-like files in zip
    for name in namelist:
        if not name.endswith('/') and any(name.lower().endswith(ext) for ext in ['.txt','.docx','.md','.text','.csv']):
            zip_file_count += 1
    # extract all to folder
    z.extractall(extract_dir)
    # gather paths
    for root, dirs, files in os.walk(extract_dir):
        for fname in files:
            if any(fname.lower().endswith(ext) for ext in ['.txt','.docx','.md','.text','.csv']):
                text_file_paths.append(os.path.join(root, fname))

# Sort for deterministic order
text_file_paths.sort()

# Prepare results containers
sentence_rows = []
file_summaries = []
unreadable_files = []

for path in text_file_paths:
    try:
        content, err = read_file_content(path)
        if content is None:
            unreadable_files.append((path, err))
            continue
        # Extract year from filename if exists
        year_search = re.search(r'20\\d{2}', os.path.basename(path))
        year = year_search.group(0) if year_search else ''
        # Determine source type by folder names (assume top-level folder names are 'news articles', 'official documents', 'scholarly works')
        rel = os.path.relpath(path, extract_dir)
        parts = rel.split(os.sep)
        source_type = parts[0] if len(parts) > 0 else ''
        media = parts[1] if len(parts) > 1 and source_type.lower().startswith('news') else ''
        sentences = split_into_sentences(content)
        num_sent = len(sentences)
        file_counter = Counter()
        for i, sent in enumerate(sentences):
            prev_sent = sentences[i-1] if i-1 >= 0 else ''
            next_sent = sentences[i+1] if i+1 < num_sent else ''
            combined_context = " ".join([prev_sent, sent, next_sent]).strip()
            row = {
                'file_path': path,
                'rel_path': rel,
                'source_type': source_type,
                'media': media,
                'year': year,
                'sentence_index': i,
                'sentence': sent,
                'context_prev': prev_sent,
                'context_next': next_sent,
            }
            # Check each concept
            any_flag = False
            for concept, kws in concept_keywords.items():
                matches = match_concept(combined_context.lower(), kws)
                row[f'{concept}_flag'] = bool(matches)
                row[f'{concept}_matches'] = "; ".join(matches)
                if matches:
                    file_counter[concept] += 1
                    any_flag = True
            row['any_concept'] = any_flag
            sentence_rows.append(row)
        file_summary = {
            'file_path': path,
            'rel_path': rel,
            'source_type': source_type,
            'media': media,
            'year': year,
            'num_sentences': num_sent,
            'num_flagged_any': sum(1 for k in sentence_rows[-num_sent:] if k['file_path']==path and k['any_concept']),
        }
        # add counts per concept
        for concept in concept_keywords.keys():
            file_summary[f'count_{concept}'] = file_counter.get(concept, 0)
        file_summaries.append(file_summary)
    except Exception as e:
        unreadable_files.append((path, str(e)))
        traceback.print_exc()

# Create DataFrames
df_sentences = pd.DataFrame(sentence_rows)
df_files = pd.DataFrame(file_summaries)

# Aggregations by source_type and by year
df_by_source = df_files.groupby('source_type')[[f'count_{c}' for c in concept_keywords.keys()]].sum().reset_index()
df_by_year = df_files.groupby('year')[[f'count_{c}' for c in concept_keywords.keys()]].sum().reset_index().sort_values('year')

# Totals
total_files = len(text_file_paths)
total_sentences = len(df_sentences)
total_flagged_sentences = df_sentences['any_concept'].sum() if not df_sentences.empty else 0
total_counts_per_concept = {c: int(df_sentences[f'{c}_flag'].sum()) for c in concept_keywords.keys()}

# Save CSV outputs
out_dir = '/mnt/data/analysis_outputs'
os.makedirs(out_dir, exist_ok=True)
csv_sentences = os.path.join(out_dir, 'analysis_sentences.csv')
csv_files = os.path.join(out_dir, 'analysis_files.csv')
csv_by_source = os.path.join(out_dir, 'analysis_by_source.csv')
csv_by_year = os.path.join(out_dir, 'analysis_by_year.csv')

df_sentences.to_csv(csv_sentences, index=False)
df_files.to_csv(csv_files, index=False)
df_by_source.to_csv(csv_by_source, index=False)
df_by_year.to_csv(csv_by_year, index=False)

# Create small examples: up to 10 example sentences per concept (unique)
examples = {}
for concept in concept_keywords.keys():
    ex = df_sentences[df_sentences[f'{concept}_flag']].drop_duplicates(subset=['sentence']).head(10)['sentence'].tolist()
    examples[concept] = ex

# Print concise summary and show top tables (first rows)
print("====== ANALYSIS SUMMARY ======")
print(f"Zip file: {zip_path}")
print(f"Extracted text files found: {total_files} (in zip: {zip_file_count} text-like files)")
print(f"Total sentences across all files: {total_sentences}")
print(f"Total sentences flagged for any neoliberal concept: {total_flagged_sentences}")
print("Counts per concept (sentence-level flags):")
for c, cnt in total_counts_per_concept.items():
    print(f" - {c}: {cnt}")
print("Unreadable files (if any):", len(unreadable_files))
if unreadable_files:
    for p, err in unreadable_files:
        print("  *", p, "->", err)

# Display small previews via dataframes (for user to inspect)
try:
    import caas_jupyter_tools as cjt
    # show sample of files summary
    preview_df_files = df_files.sort_values('num_flagged_any', ascending=False).head(20)
    cjt.display_dataframe_to_user("Top 20 files by flagged sentences", preview_df_files)
    # show top 50 flagged sentences for quick inspection
    preview_sent = df_sentences[df_sentences['any_concept']].head(50)
    cjt.display_dataframe_to_user("First 50 flagged sentences (for QA)", preview_sent[['file_path','year','sentence_index','sentence','institutional_arrangements_flag','interdependence_flag','absolute_gains_flag','shadow_of_future_flag']])
except Exception as e:
    print("Could not display interactive tables (caas_jupyter_tools unavailable):", e)

# Save examples to JSON for download
examples_path = os.path.join(out_dir, 'examples_by_concept.json')
with open(examples_path, 'w', encoding='utf-8') as f:
    json.dump(examples, f, indent=2, ensure_ascii=False)

print("\nCSV outputs saved to:", out_dir)
print(" - sentences:", csv_sentences)
print(" - files summary:", csv_files)
print(" - aggregated by source:", csv_by_source)
print(" - aggregated by year:", csv_by_year)
print(" - examples JSON:", examples_path)

# Return a structured summary as the "result"
result = {
    'total_files': total_files,
    'zip_text_file_count': zip_file_count,
    'total_sentences': total_sentences,
    'total_flagged_sentences': int(total_flagged_sentences),
    'total_counts_per_concept': total_counts_per_concept,
    'csv_sentences': csv_sentences,
    'csv_files': csv_files,
    'csv_by_source': csv_by_source,
    'csv_by_year': csv_by_year,
    'examples_json': examples_path,
    'unreadable_files': unreadable_files,
    'output_dir': out_dir
}

result